# Generated by Django 5.1.4 on 2026-06-21 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('IN', 'Dépôt'), ('OUT', 'Retrait')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='XAF', max_length=8)),
                ('provider_key', models.CharField(max_length=32)),
                ('method', models.CharField(blank=True, default='', max_length=32)),
                ('external_ref', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SETTLED', 'Réglé'), ('FAILED', 'Échoué')], default='PENDING', max_length=10)),
                ('destination', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_intent',
                'ordering': ['-created_at'],
            },
        ),
    ]
