# Generated by Django 5.1.4 on 2026-06-27 23:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('country_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('currency', models.CharField(default='XAF', max_length=8)),
                ('legal_age', models.PositiveSmallIntegerField(default=18)),
                ('kyc_level', models.CharField(choices=[('NONE', 'Aucun'), ('BASIC', 'Basique'), ('FULL', 'Complet')], default='NONE', max_length=8)),
                ('max_rake', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('gambling_allowed', models.BooleanField(default=True)),
                ('vs_ai_allowed', models.BooleanField(default=True)),
                ('allowed_payment_methods', models.JSONField(blank=True, default=list)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('reporting', models.JSONField(blank=True, default=dict)),
                ('mentions', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'compliance_jurisdiction',
            },
        ),
        migrations.CreateModel(
            name='ComplianceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_profile', to=settings.AUTH_USER_MODEL)),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='compliance.jurisdiction')),
            ],
            options={
                'db_table': 'compliance_profile',
            },
        ),
        migrations.CreateModel(
            name='ResponsibleGamblingLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('BET', 'Mise'), ('LOSS', 'Perte'), ('SESSION_TIME', 'Temps de session')], max_length=16)),
                ('period', models.CharField(choices=[('DAILY', 'Quotidienne'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuelle')], default='DAILY', max_length=8)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('effective_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rg_limits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_rg_limit',
                'indexes': [models.Index(fields=['user', 'kind', 'effective_at'], name='compliance__user_id_37188c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SelfExclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TEMPORARY', 'Temporaire'), ('PERMANENT', 'Définitive')], max_length=10)),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_exclusions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_self_exclusion',
                'indexes': [models.Index(fields=['user', 'type'], name='compliance__user_id_a6cc27_idx')],
            },
        ),
    ]
