export const TAILLE_CAMP = 7;
export const TOTAL_TROUS = TAILLE_CAMP * 2;
export const SEUIL_VICTOIRE = 40;
export const SEUIL_RARETE = 10;
export const GRAINES_BOUCLE = TOTAL_TROUS - 1;
export const TT_MAX_SIZE = 200000;

export const PROVERBES = [
  "L'eau qui coule ne revient pas à sa source.",
  "Même le lion laisse des os aux charognards.",
  "Un ventre vide n'a pas d'oreilles.",
  "La précipitation est la mère de l'échec.",
  "La sagesse se construit graine par graine.",
  "Celui qui veut tout manger finit par s'étouffer.",
  "Une seule main ne peut pas attacher un paquet.",
  "La force du baobab est dans ses racines profondes.",
  "Si tu veux aller vite, marche seul. Si tu veux aller loin, marchons ensemble.",
  "Le vieillard assis voit plus loin que le jeune homme debout.",
  "On n'apprend pas à un vieux singe à faire des grimaces.",
  "La patience est un chemin d'or.",
  "Le mensonge donne des fleurs mais pas de fruits.",
  "Petit à petit, l'oiseau fait son nid.",
  "Qui sème le vent récolte la tempête.",
  "On ne peut pas raser la tête d'un absent.",
  "La langue qui fourche fait plus de mal que le pied qui trébuche.",
  "Le silence est une force.",
  "L'erreur n'est pas un crime, c'est une leçon.",
  "Le fleuve ne remonte jamais vers sa source.",
  "Un ami est comme une source d'eau dans le désert.",
  "La vérité est comme le soleil, on ne peut pas la cacher longtemps.",
  "Le courage n'est pas l'absence de peur, mais la capacité de la vaincre.",
  "La gratitude est la mémoire du cœur.",
  "On ne peut pas empêcher le vent de souffler, mais on peut construire des moulins.",
  "La connaissance est un trésor que l'on emporte partout.",
  "Le respect se gagne, il ne se demande pas.",
  "La persévérance est la clé du succès.",
  "Un grain de maïs a toujours tort devant une poule.",
  "Si tu montes au sommet d'une montagne, n'oublie pas ceux qui t'ont aidé.",
  "La vie est un miroir, elle nous rend ce que nous lui donnons.",
  "Le temps est un grand maître.",
  "L'union fait la force.",
  "La modestie est la parure des sages.",
  "On ne peut pas attraper deux lièvres à la fois.",
  "La parole est d'argent, mais le silence est d'or.",
  "Le travail éloigne de nous trois grands maux : l'ennui, le vice et le besoin.",
  "La chance sourit aux audacieux.",
  "Il n'y a pas de raccourci pour arriver là où ça vaut la peine d'aller.",
  "La beauté est dans les yeux de celui qui regarde.",
  "Un voyage de mille lieues commence par un premier pas.",
  "La haine est un fardeau trop lourd à porter.",
  "Le pardon est une vertu.",
  "La générosité est la clé du bonheur.",
  "On ne peut pas plaire à tout le monde.",
  "La curiosité est un vilain défaut, mais une grande qualité pour apprendre.",
  "Le savoir-faire est plus important que le savoir.",
  "La discipline est le pont entre les objectifs et les accomplissements.",
  "L'imagination est plus importante que la connaissance.",
  "La créativité, c'est l'intelligence qui s'amuse.",
  "Le succès, c'est d'aller d'échec en échec sans perdre son enthousiasme.",
  "La seule façon de faire du bon travail est d'aimer ce que vous faites.",
  "Le futur appartient à ceux qui croient à la beauté de leurs rêves.",
  "N'attendez pas l'opportunité, créez-la.",
  "La meilleure façon de prédire l'avenir est de le créer.",
  "Le bonheur n'est pas quelque chose de tout fait, il vient de vos propres actions.",
  "Soyez le changement que vous voulez voir dans le monde.",
  "La vie, c'est ce qui arrive quand on a d'autres projets.",
  "Tout ce que vous pouvez imaginer est réel.",
  "L'important n'est pas ce qu'on fait de nous, mais ce que nous faisons de ce qu'on a fait de nous.",
  "La liberté commence où l'ignorance finit.",
  "Un livre ouvert est un cerveau qui parle.",
  "La culture est ce qui reste quand on a tout oublié.",
  "L'education est l'arme la plus puissante pour changer le monde.",
  "La paix n'est pas l'absence de guerre, c'est une vertu, un état d'esprit.",
  "Le plus grand voyageur est celui qui a su faire une fois le tour de lui-même."
];
