# Generated by Django 5.1.4 on 2026-06-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'paramètre de plateforme',
                'verbose_name_plural': 'paramètres de plateforme',
                'db_table': 'backoffice_platform_config',
            },
        ),
    ]
