# Generated by Django 5.1.4 on 2026-06-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSetting',
            fields=[
                ('game_key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'backoffice_game_setting',
            },
        ),
        migrations.CreateModel(
            name='ProviderSetting',
            fields=[
                ('provider_key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'backoffice_provider_setting',
            },
        ),
    ]
