# Generated by Django 5.1.4 on 2026-06-21 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_key', models.CharField(max_length=32)),
                ('opponent_type', models.CharField(choices=[('HUMAN', 'Humain'), ('AI', 'IA / Maison')], max_length=8)),
                ('timing_mode', models.CharField(choices=[('REALTIME', 'Temps réel'), ('CORRESPONDENCE', 'Différé')], max_length=16)),
                ('pairing_mode', models.CharField(choices=[('AUTO', 'Automatique (lobby)'), ('INVITE_CODE', "Code d'accès")], max_length=16)),
                ('access_code', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('access_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('stake_kind', models.CharField(choices=[('REAL', 'Réelle'), ('BONUS', 'Bonus/virtuelle')], max_length=8)),
                ('bet_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='XAF', max_length=8)),
                ('game_state', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('ACTIVE', 'En cours'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=10)),
                ('current_player', models.PositiveSmallIntegerField(default=0)),
                ('ai_level', models.CharField(blank=True, default='', max_length=16)),
                ('rake_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('end_reason', models.CharField(blank=True, choices=[('WIN', 'Victoire'), ('DRAW', 'Nul'), ('FORFEIT', 'Forfait'), ('TIMEOUT', 'Temps écoulé'), ('DISCONNECT', 'Déconnexion'), ('VOID', 'Annulé/remboursé')], default='', max_length=10)),
                ('move_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_p2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_won', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matchmaking_match',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CONNECT', 'Connexion'), ('DISCONNECT', 'Déconnexion'), ('RECONNECT', 'Reconnexion'), ('TIMEOUT_AUTOMOVE', 'Coup auto (timeout)'), ('FORFEIT', 'Forfait'), ('RESOLVE', 'Résolution'), ('VOID', 'Annulation')], max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matchmaking.match')),
            ],
            options={
                'db_table': 'matchmaking_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('player', models.PositiveSmallIntegerField()),
                ('payload', models.JSONField()),
                ('server_validated', models.BooleanField(default=True)),
                ('is_auto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='matchmaking.match')),
            ],
            options={
                'db_table': 'matchmaking_move',
                'ordering': ['seq'],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status', 'pairing_mode'], name='matchmaking_status_20a41c_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['game_key', 'status'], name='matchmaking_game_ke_2a6fc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='move',
            unique_together={('match', 'seq')},
        ),
    ]
