# Generated by Django 5.1.4 on 2026-06-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='ai_profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
