# Generated by Django 5.1.4 on 2026-06-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_match_ai_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_training',
            field=models.BooleanField(default=False),
        ),
    ]
