# Generated by Django 5.1.4 on 2026-06-28 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualUsagePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_matches_per_day', models.PositiveIntegerField(default=20)),
                ('allowed_hours', models.CharField(blank=True, default='', max_length=32)),
                ('cooldown_seconds', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bonus_virtual_usage_policy',
            },
        ),
        migrations.CreateModel(
            name='BonusGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('WELCOME', 'Bienvenue (1er dépôt)')], default='WELCOME', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bonus_grant',
                'constraints': [models.UniqueConstraint(fields=('user', 'type'), name='uniq_bonus_per_user_type')],
            },
        ),
    ]
