# Generated by Django 5.1.4 on 2026-06-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusConversionCounter',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('total_converted_real', models.DecimalField(decimal_places=2, default=0, max_digits=24)),
            ],
            options={
                'db_table': 'bonus_conversion_counter',
            },
        ),
    ]
