# Generated by Django 5.1.4 on 2026-06-21 11:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('bonus_available', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('bonus_locked', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('currency', models.CharField(default='XAF', max_length=8)),
                ('bonus_pocket_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_wallet',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait'), ('BET_LOCK', 'Mise verrouillée'), ('BET_WIN', 'Gain'), ('COMMISSION', 'Rake'), ('REFUND', 'Remboursement'), ('HOUSE_SETTLEMENT', 'Règlement Maison'), ('BONUS_GRANT', 'Octroi de bonus'), ('BONUS_CONVERSION', 'Conversion bonus→réel')], max_length=20)),
                ('pocket', models.CharField(choices=[('REAL', 'Réelle'), ('BONUS', 'Bonus/virtuelle')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='XAF', max_length=8)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SETTLED', 'Réglée'), ('FAILED', 'Échouée')], default='SETTLED', max_length=10)),
                ('match_id', models.UUIDField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_transaction',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['wallet', 'pocket'], name='wallet_tran_wallet__c13b22_idx'), models.Index(fields=['match_id'], name='wallet_tran_match_i_067dd6_idx')],
            },
        ),
    ]
